FROM python:3.6-stretch

# Below args must match host system parameters
# to produce static and media files with necessary flags

RUN groupadd --gid 1000 irc_bot && useradd -r -d /app -s /bin/bash -g irc_bot -u 1000 irc_bot
WORKDIR /app

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

USER irc_bot
WORKDIR /app
CMD ["./start.sh"]
